application: erudite-visitor-93719
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /images
  static_dir: images
- url: /.*
  script: templates.app

  
libraries:
- name: jinja2
  version: latest
    
    